version: '3.7'

services:

  rush-react:
    container_name: rush-react
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      
    stdin_open: true
    tty: true
